---
deployment:
    tasks:
        - export DEPLOYPATH=/home/alicqplp/public_html/
        - /bin/cp index.html $DEPLOYPATH
        - /bin/cp styles.css $DEPLOYPATH
        - /bin/cp script.js $DEPLOYPATH
        - /bin/cp -R pictures $DEPLOYPATH
